In [5]:
!pip install numpy


In [6]:
import numpy as np
vector=np.linspace(0,20,5)
print(vector)

[ 0.  5. 10. 15. 20.]


In [7]:
import numpy as np
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [8]:
!type pip

The system cannot find the file specified.


In [9]:
import numpy as a
list=[2,4,5,6]
a.array(list)

array([2, 4, 5, 6])

In [10]:
a.array([list,list])

array([[2, 4, 5, 6],
       [2, 4, 5, 6]])

In [11]:
a.array([[2, 4, 5, 6],
       [2, 4, 5, 6]])

array([[2, 4, 5, 6],
       [2, 4, 5, 6]])

In [13]:
a.array([[2, 4, 5, 6],
       [2, 4, 5, 6],[3,-1,6,5]])

array([[ 2,  4,  5,  6],
       [ 2,  4,  5,  6],
       [ 3, -1,  6,  5]])

In [14]:
import numpy as np
print(np.__version__)

1.21.5


In [17]:
10*a.eye(4)

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [18]:
0*a.eye(4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.zeros(shape=(4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
5*np.ones(shape=(3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [23]:
a.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
a.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a.arange(-5,10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [28]:
a.arange(-5,10,3)

array([-5, -2,  1,  4,  7])

In [30]:
a.arange(100,10,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [32]:
a.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [33]:
a.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [34]:
a.random.rand(2,3,6)

array([[[0.4574027 , 0.795952  , 0.27624093, 0.90331449, 0.4415126 ,
         0.50565162],
        [0.07270106, 0.24342628, 0.51001128, 0.58135554, 0.91552942,
         0.5110522 ],
        [0.18010861, 0.93772916, 0.79375885, 0.55764475, 0.7562431 ,
         0.1807665 ]],

       [[0.96677583, 0.23523069, 0.18005087, 0.07594071, 0.38179958,
         0.61571851],
        [0.67748851, 0.49402508, 0.74608652, 0.64320105, 0.71304022,
         0.83805184],
        [0.06945785, 0.3425154 , 0.68808249, 0.02269696, 0.74711616,
         0.5141955 ]]])

In [40]:
a.random.randint(10,50,5)

array([11, 32, 40, 21, 39])

In [35]:
mat=a.random.rand(4,5)
mat

array([[0.198404  , 0.71358807, 0.60381113, 0.48791579, 0.32756557],
       [0.80617526, 0.40278961, 0.25945898, 0.1250498 , 0.08713798],
       [0.65027816, 0.97741578, 0.75992066, 0.7209614 , 0.00419497],
       [0.43666309, 0.70013359, 0.31425943, 0.46021593, 0.30139665]])

In [36]:
type(mat)

numpy.ndarray

In [37]:
mat.size

20

In [38]:
mat.shape

(4, 5)

In [39]:
mat.reshape(2,10).shape

(2, 10)

In [42]:
arr=a.arange(50,70)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [43]:
arr.shape

(20,)

In [44]:
arr[4]

54

In [45]:
arr[-10]

60

In [47]:
arr[9]

59

In [48]:
arr[-9]

61

In [51]:
#arr[start:end]

NameError: name 'start' is not defined

In [52]:
arr[8:20]

array([58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])